In [1]:
import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [2]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
row

array([0, 1, 2])

In [4]:
mask

array([ True, False,  True, False])

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [6]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [7]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [8]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [9]:
arr1.shape

(2, 2)

In [10]:
arr2.shape

(2,)

In [11]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [13]:
"""
Expected output
 ([[4,6,8,10],
 [2,14,6,10],
 [4,16,12,18],
 [22,46,24,38]])
 """

'\nExpected output\n ([[4,6,8,10],\n [2,14,6,10],\n [4,16,12,18],\n [22,46,24,38]])\n '

In [14]:
arr1 = np.array([[2,2,2,2]]) # row vector
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [15]:
arr1 = np.array([[2],[2],[2],[2]]) #column vector
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [16]:
arr1 = 2 #
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [17]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])


1.0


In [18]:
x

array([[200, 200, 200],
       [300, 300, 300],
       [400, 400, 400]])

In [19]:
v

array([200, 300, 400])

In [20]:
v[:,None]

array([[200],
       [300],
       [400]])

In [22]:
(x / v[:,None])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
p

array([[ 0],
       [10],
       [20]])

In [25]:
q

array([10, 11, 12])

In [26]:
p+q

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [27]:
print((p + q)[1][1]) 

21


In [35]:
arr = [[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]]

In [38]:
arr = np.array(arr)
arr.shape

(2, 3, 3)

In [41]:
arr[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [42]:
arr = np.array([[[0, 1], 
             [2, 3]], 
 
            [[4, 5], 
             [6, 7]]])

In [43]:
arr[:,0:,:1]

array([[[0],
        [2]],

       [[4],
        [6]]])

In [44]:
arr=np.array([2,4,6,8,10])
c0 = arr

In [45]:
c0

array([ 2,  4,  6,  8, 10])

In [46]:
c0[0] =12
c0

array([12,  4,  6,  8, 10])

In [47]:
arr=np.array([2,4,6,8,10])
c1 = arr.view()

In [48]:
c1

array([ 2,  4,  6,  8, 10])

In [49]:
arr[0]=12
arr

array([12,  4,  6,  8, 10])

In [50]:
c1

array([12,  4,  6,  8, 10])

In [51]:
arr=np.array([2,4,6,8,10])

In [52]:
c2 = arr.copy()

In [53]:
arr

array([ 2,  4,  6,  8, 10])

In [54]:
c2

array([ 2,  4,  6,  8, 10])

In [55]:
arr[0]=12

In [56]:
arr

array([12,  4,  6,  8, 10])

In [57]:
c2

array([ 2,  4,  6,  8, 10])

In [58]:
arr = np.array([1,2,3,0,-2,4])

In [59]:
arr1 = arr*1 #deep copy

In [60]:
id(arr1), id(arr)

(4766543920, 4766544016)

In [61]:
arr1 = arr[:] #deep copy

In [62]:
id(arr1), id(arr)

(4765641872, 4766544016)

In [63]:
arr1 = arr #shallow copy

In [64]:
id(arr1), id(arr)

(4766544016, 4766544016)

In [65]:
arr1 = arr[arr > 0]
id(arr1), id(arr)

(4765641872, 4766544016)

In [66]:
arr1 = arr.reshape(2,3)
id(arr1), id(arr)

(4766547184, 4766544016)

In [67]:
arr = np.arange(16).reshape(4,4)  

print(np.split(arr, 4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [68]:
arr = np.arange(10)
np.split(arr, 3)

ValueError: array split does not result in an equal division

In [69]:
arr = np.arange(10)
np.split(arr, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [70]:
arr = np.arange(10)
np.split(arr, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [71]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]

In [72]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])


In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.hstack((arr, arr[:, [0]])).shape

(3, 4)

In [77]:
np.hstack((arr,arr[:, 0])) 

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)