In [1]:
import numpy as np

In [2]:
data = np.loadtxt("fitbit.txt", dtype="str")
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [3]:
data_T = data.T

In [4]:
date, step_count, mood, calories, sleephours, active = data.T

In [5]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [7]:
type(step_count[0])

numpy.str_

In [10]:
step_count = np.array(step_count, dtype="int") #typecast

In [11]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [13]:
#return index of higher value
step_count.argmax()

69

In [14]:
#return date for the max step count
calories[step_count.argmax()]

'243'

In [15]:
step_count.max()

7422

# Matrices

In [16]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
b=np.ones(1)
b

array([1.])

In [18]:
a*b

array([0., 1., 2., 3., 4.])

In [28]:
c = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
d = np.array([1,2,3,4,5,6]).reshape(3,2)

In [29]:
c,d

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [32]:
np.dot(c,d)  #method 1

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [34]:
np.matmul(c,d) #method 2

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [35]:
c@d #method 3

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [38]:
d

56


In [39]:
d = np.arange(1,10).reshape(1,-1)

In [40]:
d.shape

(1, 9)

In [41]:
d

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
d.flatten() #2D -> 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
d.reshape()

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
a = np.arange(1,10)

In [47]:
np.dot(a,d)

ValueError: shapes (9,) and (1,9) not aligned: 9 (dim 0) != 1 (dim 0)

In [48]:
np.dot(d,a) #pnemonic: keep higher dim on left 

array([285])

In [51]:
e = np.arange(1,10).reshape(3,-1)

In [52]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
f = np.arange(1,13).reshape(3,-1)
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
g = np.arange(1,17).reshape(4,-1)
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
mat = e.dot(f).dot(g)

In [64]:
mat

array([[1436, 1624, 1812, 2000],
       [3254, 3676, 4098, 4520],
       [5072, 5728, 6384, 7040]])

In [63]:
np.argmin(mat, axis=0)

array([0, 0, 0, 0])

In [72]:
e = [[2,3,-1],[4,3,1],[9,2,7]]
e

[[2, 3, -1], [4, 3, 1], [9, 2, 7]]

In [73]:
np.argmin(e)

2

In [74]:
np.argmin(e, axis=0)

array([0, 2, 0])

In [75]:
np.argmax(e, axis=1)

array([1, 0, 0])

## Vectorisation
-Define a vectorized function which takes or numpy arrays as inputs and returns a single numpy array or a tuple of numpy arrays.

In [76]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [99]:
def func(x):
    if x%2==0:
        return x*2
    else:
        return 0

In [100]:
func(a) # not able to take numpy array as input

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [101]:
vec_func = np.vectorize(func)

In [102]:
vec_func(a)

array([ 0,  4,  0,  8,  0, 12,  0, 16,  0, 20,  0, 24])

In [84]:
import math
math.log(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [85]:
vec_log = np.vectorize(math.log) # create a func that can take numpy

In [86]:
vec_log(a) 

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [90]:
math.pow(a,2)

TypeError: only size-1 arrays can be converted to Python scalars

In [93]:
vec_pow = np.vectorize(math.pow)

In [94]:
vec_pow(a,2)

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121.,
       144.])

In [95]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Broadcasting

In [103]:
c = np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [104]:
c[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
c[:,:2,:2]

array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])