# Agenda

- Use Case: Fitness data analysis
- 2D arrays
- Indexing and slicing
- Fancy indexing
- Aggregate functions
- Logical operations
- Fitbit soluntion

In [1]:
import numpy as np

In [2]:
data = np.loadtxt("fitbit.txt", dtype="str")
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [3]:
print(data.shape, data.ndim)

(96, 6) 2


In [4]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [6]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [7]:
a = np.array(range(16))

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
a.shape

(16,)

In [11]:
#creating a 2d array
b = np.array([[1,2,3],[4,5,6]]) #manually

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b.reshape(-1,3) # -1 dummy indices if you do not hardcode

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c = np.arange(20)

In [21]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
c.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
c.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
len(c)

20

In [26]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
c = c.reshape(5,-1)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
len(c)

5

In [31]:
c[1,2]

6

In [33]:
d = np.arange(12).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
#Transpose of a matrix
d.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [35]:
d.shape

(3, 4)

In [37]:
d.T.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Indexing and slicing

In [38]:
m1 = np.arange(1,10)
m1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
m1.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2 = np.arange(12).reshape(-1,4)

In [42]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
arr2.ndim

2

In [44]:
arr2[:,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [48]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
arr2[1:2,2:3]

array([[6]])

In [50]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [51]:
t= np.arange(1,13).reshape(3,-1)

In [52]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
t[::2,:] #chose rows 

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [54]:
t[::,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [55]:
t[0:2:2,::]

array([[1, 2, 3, 4]])

In [56]:
t[::-1,::]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [57]:
t[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [58]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
t[::-2,::]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [66]:
a = [1,2,3,4,5]
b = [8,7,6]
print(a[2 : ],b[ : :-1])


[3, 4, 5] [6, 7, 8]


In [67]:
a[2:]=b[::-1] #assignment and NOT equal to

In [68]:
a

[1, 2, 6, 7, 8]

In [69]:
c = np.array([1,2,3,4,5])
d = np.array([8,7,6])

In [70]:
c,d

(array([1, 2, 3, 4, 5]), array([8, 7, 6]))

In [72]:
c[:3] = d[::-1]

In [73]:
c

array([6, 7, 8, 4, 5])

In [76]:
a[3] = b[::-1] #a,b are list
a #list within list

[1, 2, 6, [6, 7, 8], 8]

In [77]:
c[3] = d[::-1] #c,d are ndarray

ValueError: setting an array element with a sequence.

In [79]:
# Fitbit analysis
data[-6:]

array([['04-01-2018', '702', 'Sad', '23', '3', 'Inactive'],
       ['05-01-2018', '133', 'Sad', '4', '2', 'Inactive'],
       ['06-01-2018', '153', 'Happy', '0', '8', 'Inactive'],
       ['07-01-2018', '500', 'Neutral', '0', '5', 'Active'],
       ['08-01-2018', '2127', 'Neutral', '0', '5', 'Inactive'],
       ['09-01-2018', '2203', 'Happy', '0', '5', 'Active']], dtype='<U10')

In [80]:
data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [81]:
data_T = data.T

In [82]:
data_T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [83]:
data_T.shape

(6, 96)

In [84]:
#extract the variables using transpose
date, step_count, mood, calories, sleephours, active = data.T

In [85]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [86]:
step_count = np.array(step_count, dtype = "int64")
step_count.dtype

dtype('int64')

In [87]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [88]:
date = data[:,0]
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [89]:
calories = np.array(calories, dtype = "int64")
calories.dtype

dtype('int64')

In [90]:
sleephours = np.array(sleephours, dtype = "int64")
sleephours.dtype

dtype('int64')

In [91]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [92]:
np.unique(active)

array(['Active', 'Inactive'], dtype='<U10')

In [93]:
arr1 = np.arange(12).reshape(3,4)

In [95]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr1<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [97]:
arr1[arr1<6] #returns an 1d array!!!

array([0, 1, 2, 3, 4, 5])

In [98]:
s = np.array([300,456,556,3345])
s

array([ 300,  456,  556, 3345])

In [99]:
s[[True, False, True, True]]

array([ 300,  556, 3345])

In [103]:
m = np.array(["sad","happy","sad","happy"])
m

array(['sad', 'happy', 'sad', 'happy'], dtype='<U5')

In [104]:
m == "happy"

array([False,  True, False,  True])

In [106]:
s[m=="happy"]

array([ 456, 3345])

In [107]:
a = np.arange(12).reshape(3,4)


In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
np.sum(a)

66

In [110]:
np.sum(a, axis=0) #axis =0 row-wise 

array([12, 15, 18, 21])

In [111]:
np.sum(a, axis=1) #axis =1 col-wise

array([ 6, 22, 38])

In [113]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

In [114]:
a,b

(array([1, 2, 3, 4, 5]), array([2, 3, 4, 5, 6]))

In [115]:
a<b

array([ True,  True,  True,  True,  True])

In [116]:
np.any(a<b)

True

In [117]:
np.all(a<b)

True

In [119]:
np.where(a>0,+1,-1) #return +1 if a>0 else -1

array([1, 1, 1, 1, 1])

In [120]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [121]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [124]:
step_count_happy = step_count[mood=="Happy"]
step_count_happy

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [125]:
len(step_count), len(step_count_happy), len(step_count[mood=="Sad"])

(96, 40, 29)

In [127]:
#average step count when he was happy, sad, neutral
print(np.mean(step_count_happy))
print(np.mean(step_count[mood=="Sad"]))
print(np.mean(step_count[mood=="Neutral"]))

3392.725
2103.0689655172414
3153.777777777778


In [134]:
# if the step count is >4000, returns the no. of days the guy was happy, sad, neutral

mask = step_count > 4000
mood[mask]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [135]:
np.unique(mood[mask], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [136]:
np.unique(mood[step_count<2000], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))