In [2]:
import numpy as np
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

elementwise operation

In [7]:
b = np.ones(10) + 1
b


array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [8]:
b - a

array([ 2.,  1.,  0., -1., -2., -3., -4., -5., -6., -7.])

In [9]:
b*a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [11]:
# matrix multiplication


c = np.diag([1,2,3,4,5])
c

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [12]:
c*c

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [13]:
c.dot(c)  #either works C.c as linear algebra

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [14]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,1])

In [15]:
a ==b

array([False, False, False, False])

In [17]:
np.array_equal(a,b)

False

In [18]:
np.array_equiv(a,b)

False

In [16]:
a > b

array([False, False, False,  True])

## Logical operations

In [19]:
a = np.array([1,0,0,1], dtype = "bool")
b = np.array([0,0,1,1], dtype = "bool")


In [20]:
np.logical_or(a,b)

array([ True, False,  True,  True])

In [21]:
np.logical_and(a,b)

array([False, False, False,  True])

## Transcendtal functions

In [23]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
np.log(a)

/var/folders/21/vgybxt6529g5wrtxj6dvczdm0000gn/T/ipykernel_53078/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [25]:
a

array([0, 1, 2, 3, 4])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [28]:
a

array([0, 1, 2, 3, 4])

## Shape mismatch

In [29]:
a = np.arange(4)
a + np.arange(3)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

# Basic reductions

In [31]:
# computing sums

a = np.arange(4)
print(a)
np.sum(a)

[0 1 2 3]


6

In [32]:
x = np.array([[1,2],[3,4]])

In [33]:
x

array([[1, 2],
       [3, 4]])

In [34]:
x.sum(axis =0) # row wise sum

array([4, 6])

In [35]:
x.sum(axis =1) # column wise sum

array([3, 7])

In [36]:
x = np.array([1,3,2])
x.min()


1

In [37]:
x.max()

3

In [38]:
x.argmin() #position of min elecment in x

0

In [39]:
x.argmax()

1

## Logical operations

In [40]:
np.all([True, False, True]) # if all of them are true returns true, otherwise return false

False

In [41]:
np.any([True, False, True]) # if any is true return true

True

In [45]:
a = np.zeros(4,4)
np.any(a !=0)

TypeError: Cannot interpret '4' as a data type

In [46]:
np.all(a==a)

True

a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
np.all((a<=b)& (b<=c))
#((a<=b)&(b<=c)).all()

## statistics

In [57]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

a.mean()

2.0

In [58]:
np.mean(a)

2.0

In [60]:
y = np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.median(y, axis =0) #row wise median

array([2.5, 3.5, 4.5])

In [66]:
np.median(y, axis =1) #column wise median

array([2., 5.])

In [67]:
x.std()

0.816496580927726

In [68]:
np.std(x)

0.816496580927726

# File handling

In [72]:
# load data into numpy array object

data = np.loadtxt('populations.txt') # load??


In [70]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [76]:
data.T # transpose 

array([[ 1900.,  1901.,  1902.,  1903.,  1904.,  1905.,  1906.,  1907.,
         1908.,  1909.,  1910.,  1911.,  1912.,  1913.,  1914.,  1915.,
         1916.,  1917.,  1918.,  1919.,  1920.],
       [30000., 47200., 70200., 77400., 36300., 20600., 18100., 21400.,
        22000., 25400., 27100., 40300., 57000., 76600., 52300., 19500.,
        11200.,  7600., 14600., 16200., 24700.],
       [ 4000.,  6100.,  9800., 35200., 59400., 41700., 19000., 13000.,
         8300.,  9100.,  7400.,  8000., 12300., 19500., 45700., 51100.,
        29700., 15800.,  9700., 10100.,  8600.],
       [48300., 48200., 41500., 38200., 40600., 39800., 38600., 42300.,
        44500., 42100., 46000., 46800., 43800., 40900., 39400., 39000.,
        36700., 41800., 43300., 41300., 47300.]])

In [75]:
years, hares, cats, carrots = data.T # transpose and then column to variable
years

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [78]:
# the mean poulation over time
populations = data[: , 1 : ]  #from row 0 to end , from colum 1 to end
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [79]:
populations.std(axis = 0)  # 0 -> rows, 1 = columns

array([20897.90645809, 16254.59153691,  3322.50622558])

In [80]:
# which has the highest population is

np.argmax(populations, axis =1)  # 0 = ahare, 1 = cat, 2 = carrot

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])


## Tile method (Broadcasting)


In [83]:
# tile function which piles up the tiles

a = np.tile(np.arange(0, 40, 10), (3,1)) 

#np.aranege creates and 1D array with elecment [0, 40] in steps of 10. tile replicates this array 3 times row and 1 col
a


array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [84]:
a.T

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [86]:
a = np.tile(np.arange(0, 40, 10), (3,4)) 
#replicate 3 times in row and 4 times in
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [93]:

b = np.array([0,1,2])
print(b)
b.shape
# notice (3,) "1D" array (vector) with 3 elements 

[0 1 2]


(3,)

In [94]:
a = np.tile(np.arange(0, 40, 10), (3,1)) 
print(a.T)
a.T.shape

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


(4, 3)

In [92]:
a.T + b
# summing (4*3) and (1*3) matrices

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [98]:
a = np.arange(0,40,10)
print(a)
a.shape

[ 0 10 20 30]


(4,)

In [99]:
print(a.T)
a.T.shape  # 1D array (vector)

[ 0 10 20 30]


(4,)

# 1d -> 2d array

In [100]:
a = a[: , np.newaxis]  # adds a new axis 2D array
print(a)
a.shape

[[ 0]
 [10]
 [20]
 [30]]


(4, 1)

In [101]:
a.T

array([[ 0, 10, 20, 30]])

In [102]:
a.T.shape

(1, 4)

In [103]:
b

array([0, 1, 2])

In [105]:
b.shape

(3,)

In [107]:
a+b        #counter intuitive!!! #broadcasting worked

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [108]:
(a+b).shape   

(4, 3)

In [109]:
a = np.arange(0,40,10)
print(a)
a.shape

[ 0 10 20 30]


(4,)

In [110]:
b

array([0, 1, 2])

In [111]:
a +b #broadcasting failed

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

# Array Shape manipulation


## flatenning

In [112]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [113]:
a.ravel()  #return a contiguos flattened array

array([1, 2, 3, 4, 5, 6])

In [114]:
print(a.T)
a.T.shape

[[1 4]
 [2 5]
 [3 6]]


(3, 2)

In [115]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

## reshaping

In [117]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [119]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
b[0,0] = 100
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [124]:
a   # beware and note...reshape may also return a copy

array([[100,   2,   3],
       [  4,   5,   6]])

# adding a dimension

indexing with the np.newaxis object allows to add an axis to an array

In [133]:
z = np.array([1,2,3])
print(z)
z.shape

[1 2 3]


(3,)

In [134]:
z = z[: , np.newaxis]
print(z)
z.shape

[[1]
 [2]
 [3]]


(3, 1)

## Dimension Shuffling

In [138]:
a = np.arange(24)  
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [140]:
a = np.arange(0,24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [142]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [144]:
a.shape  # 4 matrices of sixe (3*3)

(4, 3, 2)

In [145]:
a[0,2,1] # value of first matrix in 2nd row and 1st column

5

## Resizing

In [152]:
a = np.arange(4)
print(a)
a.shape

[0 1 2 3]


(4,)

In [153]:
a.resize((8,))   # fills 0 to increase size to 8

In [154]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [157]:
b = a #creates another array referecing to memory location in a

a.resize((10,))
#throws error since it must not be referred to someone else

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

## sorting data

In [164]:
# sorting along an axis

a = np.array([[1,3,2],[4,3,2]])
a.sort(axis = 1)  # row wise sort default
a

array([[1, 2, 3],
       [2, 3, 4]])

In [167]:
a = np.array([[1,3,2],[4,5,2], [2,1,4]])

a

array([[1, 3, 2],
       [4, 5, 2],
       [2, 1, 4]])

In [168]:
a.sort(axis =0) 

In [169]:
a

array([[1, 1, 2],
       [2, 3, 2],
       [4, 5, 4]])

In [170]:
# sorting with fancy indexing
a = np.array([4,3,2,1])
a

array([4, 3, 2, 1])

In [171]:
j = np.argsort(a)  #return the position of the unsorted array 
j  # 1, 2, 3, 4 are in pos 3,2,1,0 pos

array([3, 2, 1, 0])

In [172]:
a[j]  #returns the sorted array

array([1, 2, 3, 4])

In [175]:
a = np.array([[4,3,0,2], [2,3,4,5]])
print(a)
a.shape

[[4 3 0 2]
 [2 3 4 5]]


(2, 4)

In [177]:
k= np.argsort(a, axis = 1)

In [178]:
k

array([[2, 3, 1, 0],
       [0, 1, 2, 3]])

In [182]:
a

array([[4, 3, 0, 2],
       [2, 3, 4, 5]])

In [184]:
a[1,3]

5

In [185]:
k.shape

(2, 4)

In [186]:
a[k]

IndexError: index 2 is out of bounds for axis 0 with size 2

# squeeze

In [200]:
x = np.array([[[0], [1], [2]]])
print(x)
x.shape

[[[0]
  [1]
  [2]]]


(1, 3, 1)

In [201]:
x = np.squeeze(x, axis=0)# Remove axes of length one from a. the axis has to have size 1
print(x)
x.shape

[[0]
 [1]
 [2]]


(3, 1)

In [202]:
x = np.squeeze(x, axis=1)# Remove axes of length one from a. the axis has to have size 1
print(x)
x.shape

[0 1 2]


(3,)

In [210]:
y = np.arange(10)
print(y)
print(y.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)


In [211]:
y = y[: , np.newaxis]
print(y)
print(y.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [212]:
y = y[: , np.newaxis]
print(y)
print(y.shape)

[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]

 [[9]]]
(10, 1, 1)


In [213]:
y = np.squeeze(y, axis =1)  #squeezee dim with size 1

In [215]:
print(y)
y.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


(10, 1)

In [216]:
y = np.squeeze(y, axis =1)

In [217]:
print(y)
y.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)