In [1]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [2]:
type(a)

list

In [3]:
import numpy as np


In [4]:
a = [1,2,3,4,5]


In [5]:
arr =[]
for i in a:
    arr.append(i*i)
arr

[1, 4, 9, 16, 25]

In [6]:
#list comprehensions
[i*i for i in a]

[1, 4, 9, 16, 25]

In [7]:
b = np.array(a)

In [8]:
b

array([1, 2, 3, 4, 5])

In [9]:
type(b)

numpy.ndarray

In [10]:
b**2

array([ 1,  4,  9, 16, 25])

In [13]:
#2D array
c = np.array([[1,2,3], [4,5,6]]) #nested list

In [14]:
type(c)

numpy.ndarray

In [15]:
c.ndim

2

In [16]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
d.ndim

2

In [19]:
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
e.ndim

3

In [21]:
l = range(1000)
list(l)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [23]:
%timeit [i**2 for i in l]

274 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [24]:
npl = np.array(range(10000))

In [26]:
%timeit npl**2

4.21 µs ± 57.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
c.shape

(2, 3)

In [28]:
arr = np.arange(1,5,0.7)

In [29]:
arr

array([1. , 1.7, 2.4, 3.1, 3.8, 4.5])

In [30]:
np.array(["nafis",1,3])

array(['nafis', '1', '3'], dtype='<U21')

In [31]:
z = np.array([1,2,3,4])
z.dtype

dtype('int64')

In [33]:
z = np.array([1,2,3,4], dtype ="float")
print(z)
z.dtype

[1. 2. 3. 4.]


dtype('float64')

In [34]:
z = np.array([1,2,3,4])
z.dtype

dtype('int64')

In [36]:
z.astype("float")

array([1., 2., 3., 4.])

In [37]:
z

array([1, 2, 3, 4])

In [39]:
z[0]

1

In [40]:
z[[0,3]]#subarray

array([1, 4])

In [41]:
z

array([1, 2, 3, 4])

In [42]:
z < 3

array([ True,  True, False, False])

In [43]:
z[z<3]

array([1, 2])

In [44]:
!pip install gdown

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://git

In [45]:
score= np.loadtxt('survey.txt', dtype="int") 

In [46]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [47]:
type(score)

numpy.ndarray

In [48]:
score.shape

(1167,)

In [49]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [51]:
score.min()

1

In [52]:
score.max()

10

In [53]:
score.mean()

7.250214224507284

In [54]:
len(score)

1167

In [55]:
detractors = score[score<=7]
detractors

array([7, 5, 4, 7, 4, 7, 5, 7, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 7, 4, 1,
       4, 1, 7, 5, 5, 1, 1, 7, 4, 1, 5, 4, 7, 1, 1, 4, 1, 5, 1, 7, 4, 4,
       1, 7, 1, 7, 1, 1, 1, 7, 1, 7, 1, 4, 7, 7, 1, 1, 5, 5, 7, 5, 4, 4,
       7, 1, 4, 7, 1, 4, 1, 7, 5, 1, 1, 7, 5, 4, 4, 7, 7, 4, 4, 1, 4, 7,
       5, 4, 7, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 7, 7, 7, 4, 5, 4, 1, 1, 7,
       7, 1, 1, 7, 7, 7, 4, 1, 7, 7, 4, 4, 5, 4, 1, 1, 1, 1, 5, 4, 7, 7,
       5, 7, 7, 5, 4, 7, 7, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 7, 5, 5, 4, 5,
       5, 5, 1, 4, 1, 5, 7, 5, 1, 5, 1, 1, 5, 5, 4, 4, 7, 7, 1, 4, 4, 4,
       1, 7, 1, 7, 7, 4, 4, 4, 5, 5, 7, 1, 7, 1, 4, 1, 7, 4, 1, 4, 1, 7,
       4, 1, 4, 1, 5, 4, 4, 5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 7, 5, 7, 7,
       5, 5, 4, 5, 7, 4, 4, 7, 1, 4, 7, 7, 7, 4, 4, 4, 5, 1, 7, 7, 5, 5,
       1, 4, 4, 5, 1, 1, 7, 4, 7, 5, 5, 5, 7, 1, 4, 5, 5, 4, 7, 1, 5, 5,
       5, 1, 1, 7, 5, 5, 1, 7, 7, 7, 1, 7, 1, 4, 7, 5, 5, 4, 7, 7, 4, 7,
       4, 5, 1, 4, 1, 4, 5, 4, 5, 7, 5, 1, 5, 1, 5,

In [56]:
promoters = score[score>8]
promoters

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [64]:
det = detractors.shape[0]

In [65]:
pro= promoters.shape[0]

In [63]:
total = score.shape[0]
total

1167

In [66]:
percent_promoters = pro/total*100
percent_promoters

52.185089974293064

In [68]:
percent_detractors = det/total*100
percent_detractors

38.988860325621246

In [69]:
#nps = net promotion score
nps = percent_promoters - percent_detractors
nps

13.196229648671817